packages:
  - "apps/*"
  - "packages/*"
overrides:
  postcss: "^8.5.23"
allowBuilds:
  "@parcel/watcher": true
  "@prisma/client": true
  "@prisma/engines": true
  "@scarf/scarf": true
  "prisma": true
  "unrs-resolver": true
  "@nestjs/core": true
  "bcrypt": true
  "esbuild": true
